name: Format Check

# Run on all push and pull requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-check:
    name: Run format check
    uses: nasa/cFS/.github/workflows/format-check.yml@main